name: Lint and Test

on:
    push:
        branches:
            - master

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1

            - name: Install modules
              run: yarn

            - name: Lint Client
              continue-on-error: true
              run: |-
                  cd client
                  yarn
                  yarn lint

            - name: Type Client
              continue-on-error: true
              run: |-
                  cd client
                  yarn
                  yarn type

            - name: Lint Server
              continue-on-error: true
              run: |-
                  cd server
                  yarn
                  yarn lint

            - name: Type Server
              continue-on-error: true
              run: |-
                  cd server
                  yarn
                  yarn type
